# Generated by Django 5.2.4 on 2025-07-24 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CVE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_id', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('severity', models.CharField(max_length=20)),
                ('cvss_score', models.FloatField(blank=True, null=True)),
                ('published_date', models.DateTimeField()),
                ('last_modified', models.DateTimeField()),
                ('references', models.TextField(blank=True)),
            ],
        ),
    ]
