# Generated by Django 5.2.4 on 2025-07-24 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cve_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cve',
            name='severity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
